version: '2.0'
services: 
  influx:
    image: influxdb:1.5
    ports:
    - "8086:8086"
    volumes: 
    - "./data:/var/lib/influxdb"
  web:
    image: php:7.2-apache 
    ports: 
    - "80:80"
    volumes:
    - "./src:/var/www/html"
    
